- name: Remove application and configuration to create clean environment
  become: yes
  shell: |
    rm -rf /alf && rm -rf /etc/alf && rm -rf /var/run/alf
    SERVICE_NAME="alf"
    if systemctl --all --type=service | grep -q "$SERVICE_NAME"; then
        systemctl stop "$SERVICE_NAME"
        systemctl disable "$SERVICE_NAME"
        rm "/etc/systemd/system/${SERVICE_NAME}.service"
        systemctl daemon-reload
        systemctl reset-failed
    fi

- name: Add group named alf
  group:
    name: alf
    state: present

- name: Add user named alf
  user:
    name: alf
    group: alf
    state: present
    shell: /bin/bash
    createhome: yes

- name: Start and enable redis service
  service:
    name: redis
    state: started
    enabled: yes

- name: Copy rabbitmq-env.conf file
  copy:
    src: rabbitmq-env.conf
    dest: /etc/rabbitmq/rabbitmq-env.conf
    owner: root
    group: root
    mode: 0644

- name: Start and enable rabbitmq-server service
  service:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: Enable web management interface
  command: rabbitmq-plugins enable rabbitmq_management

- name: Download rabbitmqadmin
  get_url:
    url: "http://localhost:15672/cli/rabbitmqadmin"
    dest: "/tmp/rabbitmqadmin"
    mode: '0755'

- name: Move rabbitmqadmin to /usr/bin
  command: mv /tmp/rabbitmqadmin /usr/bin/
  args:
    creates: /usr/bin/rabbitmqadmin

- name: Download rmq_reconfigure.sh script
  get_url:
    url: "https://raw.githubusercontent.com/CESNET/dp3/new_dp3/scripts/rmq_reconfigure.sh"
    dest: "/tmp/rmq_reconfigure.sh"
    mode: '0700'

- name: Run rmq_reconfigure.sh script
  command: sh /tmp/rmq_reconfigure.sh alf 2

- name: Run dp3 configuration for nginx
  become: yes
  shell: |
    source /dp3-venv/bin/activate && $(which dp3) config nginx --hostname {{ server_hostname }} --app-name {{ app_name }} --www-root {{ www_root }}
  vars:
    server_hostname: grappa.liberouter.org
    app_name: alf
    www_root: /var/www/dp3

- name: Start and enable nginx service
  service:
    name: nginx
    state: started
    enabled: yes

- name: Ensure firewalld is not masked
  command: systemctl unmask firewalld

- name: Ensure firewalld is enabled
  systemd:
    name: firewalld
    enabled: yes

- name: Ensure firewalld is running
  systemd:
    name: firewalld
    state: started

- name: Open port 80/tcp
  firewalld:
    port: 80/tcp
    permanent: true
    state: enabled

- name: Reload firewalld
  command: firewall-cmd --reload

- name: Create DP3 application
  shell: |
    source /dp3-venv/bin/activate && $(which dp3) setup /alf alf

- name: Change ownership of DP3 app folder to alf user
  become: yes
  file:
    path: /alf
    owner: alf
    group: alf
    recurse: yes

- name: Create /var/run/alf folder of user and group alf
  file:
    path: /var/run/alf
    state: directory
    owner: alf
    group: alf
    mode: 0755

- name: Copy MongoDB setup file
  copy:
    src: database.yml
    dest: /alf/config/database.yml
    owner: alf
    group: alf
    mode: 0644

- name: Copy history manager config file
  copy:
    src: history_manager.yml
    dest: /alf/config/history_manager.yml
    owner: alf
    group: alf
    mode: 0644

- name: Remove example db_entities folder
  become: yes
  file:
    path: /alf/config/db_entities
    state: absent

- name: Copy db_entities folder
  copy:
    src: db_entities
    dest: /alf/config/db_entities
    owner: alf
    group: alf
    mode: 0644

- name: Create folder for datapoints history
  file:
    path: /data/datapoints
    state: directory
    owner: alf
    group: alf
    mode: 0755

- name: Setup supervisor control of all DP3 processes
  shell: |
    source /dp3-venv/bin/activate && sudo $(which dp3) config supervisor --config /alf/config --app-name alf

- name: Reload units
  become: yes
  shell: |
    systemctl daemon-reload

- name: Start and enable alf application
  systemd:
    name: alf
    state: started
    enabled: yes





