entity:
  id: flow_unlabeled
  name: unlabeled flow
  key_data_type: int64
  auto_create_record: true
  snapshot: true
attribs:
  features:
    name: features
    description: A JSON containing the features of the flow
    type: plain
    data_type: json
  ip_src:
    name: ip_src
    description: Source IP address
    type: plain
    data_type: string
  ip_dst:
    name: ip_dst
    description: Destination IP address
    type: plain
    data_type: string

  
  
  




