entity:
  id: flow
  name: Entity for network flow
  key_data_type: int64
  auto_create_record: true
  snapshot: true
attribs:
  features:
    name: features
    description: A JSON containing the features of the flow
    type: plain
    data_type: json
  characteristics:
    name: characteristics
    description: A JSON containing the characteristics of the flow
    type: plain
    data_type: json
  state:
    name: state
    description: The state of the flow
    type: plain
    data_type: string
  qod:
    name: qod
    description: The quality of dataset scoring
    type: plain
    data_type: json
    

